baseURL: "https://kilpen.dev"
theme: "up-business-theme"
languageCode: "en-us"

title: "KilPen Technical Services"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "KilPen Tech"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "up-arrow.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "4725 Bougainville Dr. #109, Honolulu, Hawaii 96818"

  contact:
    - "trungkienspktnd@gamail.com"
    - "123.456.7890"

  copyright: "© 2025 KilPen Technical Services LLc., All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About Us"
      url: "/#"
      weight: 2

    - name: "Our Services"
      url: "/#"
      weight: 3

    - name: "Our Solutions"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
